### ISSUE TITLE
Feature Request: ecobee Premium air quality sensor

### ISSUE THREAD

**Issue by cswelin** [UniversalDevicesInc-PG3/udi-poly-ecobee#4]
Since the new Thermostat has a Air Quality sensor it would be nice to expose this.

The value can be found under the `runtime` object 

`actualCO2`: The last reported CO2 parts per million
`actualVOC`: The last reported VOC parts per million 
`actualAQAccuracy` the last reported Air Quality Accuracy measurement.  A value between 0 and 3, where 3 represents fully calibrated.
`actualAQScore`  The last reported Air Quality Score measurement, value 0-5000
```
"actualVOC": 6046,
"actualCO2": 1480,
"actualAQAccuracy": 4,
"actualAQScore": 348,
```

and if the device doesn't support the sensor

```
"actualVOC": -5002,
"actualCO2": -5002,
"actualAQAccuracy": 0,
"actualAQScore": -5002,
```

Now the mobile also displays a "Excellent, Good, or Poor", if you wanted to match that logic there's a comma delimited string in the energy object (requires `includeEnergy: true` in the thermostat fetch) `airQualityPreferences` that looks like: 
`"airQualityPreferences": "aqGood:101,aqPoor:201,vocGood:1601,vocPoor:7001,co2Good:753,co2Poor:1753"`

in the AQ example:
```
Excellent where 0 <= x < 101
Good where 101<= x < 201
Poor where 201 <= x
```

Hope this is helpful, feel free to DM in Slack as well (@cswelin) if you any question or like more examples.

**Comment by jimboca** [comment]
Thanks for the excellent details, I'll try to get to this in the next few weeks. It will likely take a few iterations with you to get it all working since I don't have access to a new device.

**Comment by cswelin** [comment]
No problem, can also invite you to an "ecobee home" with a device on it.

**Comment by ziebelje** [comment]
@cswelin 

![image](https://user-images.githubusercontent.com/3288812/176955598-08f0acae-1e0f-4165-886d-da886d2291ad.png)
Does that top chart reference "Air Quality" and what is the numerical range? 

I'm looking to replicate that in beestat. Today I am showing a TVOC grid but if the colored bar on ecobee represents overall Air Quality I think it would make more sense to change it.

![image](https://user-images.githubusercontent.com/3288812/176956085-5db8d328-dfe3-4b3b-8bb2-1a42727943bc.png)

**Comment by cswelin** [comment]
> @cswelin
> 
> ![image](https://user-images.githubusercontent.com/3288812/176955598-08f0acae-1e0f-4165-886d-da886d2291ad.png) Does that top chart reference "Air Quality" and what is the numerical range?
> 
> I'm looking to replicate that in beestat. Today I am showing a TVOC grid but if the colored bar on ecobee represents overall Air Quality I think it would make more sense to change it.
> 
> ![image](https://user-images.githubusercontent.com/3288812/176956085-5db8d328-dfe3-4b3b-8bb2-1a42727943bc.png)

Yes that represents Air quality, the range should be from 0 to 350

**Comment by ziebelje** [comment]
> Yes that represents Air quality, the range should be from 0 to 350

I'm sure this wasn't up to you, but do you know any of the reasoning behind this?
1. Since TVOCs are the only *actual* measurement, why is there a separate air quality metric? I guess you could argue that it's *also* based off of CO2, but CO2 is estimated, not calculated, so it doesn't really make sense.
2. Why is the range from 0-350? If we're doing arbitrary numbers here, 0-255 is better for database storage (depends on the engine I guess), and 0-100 makes more sense to humans.

**Comment by cswelin** [comment]
> > Yes that represents Air quality, the range should be from 0 to 350
> 
> I'm sure this wasn't up to you, but do you know any of the reasoning behind this?
> 
> 1. Since TVOCs are the only _actual_ measurement, why is there a separate air quality metric? I guess you could argue that it's _also_ based off of CO2, but CO2 is estimated, not calculated, so it doesn't really make sense.
> 2. Why is the range from 0-350? If we're doing arbitrary numbers here, 0-255 is better for database storage (depends on the engine I guess), and 0-100 makes more sense to humans.

The sensor the device uses reports it’s own IAQ value, so I’m assuming it’s based on its  data sheet.

**Comment by ziebelje** [comment]
@cswelin Thanks; appreciate your insights!
@jimboca Sorry to hijack the thread. I hope the discussion was at least somewhat helpful. :)

**Comment by jimboca** [comment]
No worries, all good information. Hopefully I can get to this soon.

**Comment by jimboca** [comment]
This is released to Beta, please install in a new slot from the Non-Production store and let me know how it looks.
I haven't added the AQ Excellent, Good, Poor yet, that one will be tricky since I don't have this thermostat so mine doesn't return that info in energy.
