### ISSUE TITLE
Installed Ecobee 3.1.4 on Polyglot 3.1.23 and no PIN

### ISSUE THREAD

**Issue by phenneberry007** [UniversalDevicesInc-PG3/udi-poly-ecobee#8]
Ecobee has been working fine since I installed last year.
Upgraded Polyglot in July and all continued to work fine.
Lost power yesterday, when Polyglot restarted, all nodeserves working fine except Ecobee.
Tried reinstalling, no success - would start and then stop 2-3 seconds later
Uninstalled, waiting 10 min for all to cleanup and then reinstalled.  Clicked start but no PIN.
Looked at log and it shows 
File "/var/polyglot/pg3/ns/000db9593250_1/./ecobee-poly.py", line 7, in <module>

**Comment by jimboca** [comment]
I need to see the full traceback, but my guess is you are on PG3 and will need to upgrade to PG3x. It looks like it could be an issue we saw in PG3 that they decided not to investigate since it's working properly in PG3x.
